app/student/forms.py
from flask.ext.wtf import Form
from wtforms import IntegerField,StringField, PasswordField, BooleanField, SubmitField,SelectField,FieldList,FormField,DecimalField
from wtforms.validators import Required, Length, Email, Regexp, EqualTo
from wtforms import ValidationError
from ..models import User,Course,Teach,Task,Teach

class tForm(Form):
	pass

app/student/__init__.py
from flask import Blueprint

student = Blueprint('student', __name__)

from . import views

app/student/views.py
from flask import render_template, redirect, request, url_for, flash
from flask.ext.login import login_user, logout_user, login_required, \
    current_user
from . import student
from .. import db
from ..models import User,Course,Teach,Learn,Grade
from ..decorators import student_required

@student.route('/student/<userno>',methods=['GET','POST'])
@login_required
@student_required
def user(userno):
	user = User.query.filter_by(no=userno,permission=2).first()
	if user is None:
		abort(404)
	learns= Learn.query.filter_by(no=user.no).all()

	total_credit = 0
	stuview=[]
	for learn in learns:
		stuviewline={}
		stuviewline['grade']=learn.grade
		teachlearn = Teach.query.filter_by(id=learn.lesson).first()
		stuviewline['cname'] = teachlearn.cname
		course = Course.query.filter_by(cname=teachlearn.cname).first()
		stuviewline['chour'] = course.credithour
		if learn.grade!=0:
			total_credit += course.credithour
		stuview.append(stuviewline)

	if 'submit' in request.form and request.method=='POST':
		 return redirect(request.args.get('next') or url_for('student.lesson',user=userno))

	return  render_template('student/student.html',stuview=stuview,student=user,tc=total_credit) 

@student.route('/lesson/<user>',methods=['GET','POST'])
@login_required
@student_required
def lesson(user):
	student=User.query.filter_by(no=user,permission=2).first()
	teachs = Teach.query.all()
	learned = Learn.query.filter_by(no=student.no).all()
	choices=[]
	for teach in teachs:
		choice={}
		choice['id']=teach.id	#teach id
		choice['cname']=teach.cname	#course name
		teacher = User.query.filter_by(no=teach.no,permission=1).first()
		choice['tname']=teacher.name	#teacher.name
		course = Course.query.filter_by(cname=teach.cname).first()
		choice['chour']=course.credithour #credit hour
		choice['choosed']=False		#whether has choosed
		for learns in learned:
			if learns.lesson == teach.id:
				choice['choosed']=True	
				break
		choices.append(choice)
	
	if 'lesson' in request.form and request.method=='POST':
		if request.form['lesson'] == 'choose':
			newlearn = Learn(no=student.no,lesson=request.form['id'],grade=0)
			db.session.add(newlearn)
			db.session.commit()
		if request.form['lesson'] == 'delete':
			db.session.execute("PRAGMA foreign_keys=ON")
			oldlearn = Learn.query.filter_by(no=student.no,lesson=request.form['id']).first()
			db.session.delete(oldlearn)
			db.session.commit()
		total_score = 0
		chour = 0
		for l,t,c in db.session.query(Learn,Teach,Course).filter(Learn.no == student.no,
							Learn.lesson==Teach.id,
							Teach.cname==Course.cname):
			if l.grade!=0:
				total_score += l.grade*c.credithour
				chour += c.credithour
		if chour != 0:
			student.grade = round(total_score/chour,2)
		else:
			student.grade = 0
		db.session.add(student)
		db.session.commit()
		return redirect(request.args.get('next') or url_for('student.lesson',user=user))


	return  render_template('student/lesson.html',choices=choices) 

app/templates/student/lesson.html
  {% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}CS - Student{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Long live Long learn,{{ current_user.name }} </h1>
    <p>ID: {{current_user.no}}</p>
</div>

<head>
<meta charset="utf-8">
<style type="text/css">
table.gridtable {
	font-family: verdana,arial,sans-serif;
	font-size:600;
	color:#333333;
	margin-top: 30px;
	margin-left:  20px;
}
table.gridtable th {
	width: 400px;
	padding: 8px;
	background-color: #efefef;
}
table.gridtable td {
	width: 400px;
	padding: 8px;
	background-color: #ffffff;
}
</style>
</head>

<div>
   	<table class='gridtable'>
   		<tr><th>Course</th>
   		<th>Teacher</th>
   		<th>学分</th></tr>
   		{%for choice in choices%}
          <form action='' method="POST">
   		<tr><td>{{choice.cname}}</td>
   		<td>{{choice.tname}}</td>
   		<td>{{choice.chour}}</td> 
              <td> 
              <input type="hidden" value={{choice['id']}} name='id'>
              {% if choice.choosed%}
              <input type="submit" name='lesson' value='delete'>
              {%else%}  
              <input type='submit' name="lesson" value="choose">
               {%endif%}</td>
               </form>
        </tr>
   		{%endfor%}
   	</table>
     <p>Finished choosed? <a href="{{ url_for('student.user',userno=current_user.no) }}">Click here to return</a>.</p>
    </div>
{% endblock %} 

app/templates/student/student.html
  {% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}CS - Student{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Hello,{{ current_user.name }} </h1>
    <p>ID: {{current_user.no}}</p>
</div>
<p>>>My Lessons and Grades>>></p>
<head>
<meta charset="utf-8">
<style type="text/css">
table.gridtable {
	font-family: verdana,arial,sans-serif;
	font-size:600;
	color:#333333;
	margin-top: 30px;
	margin-left:  20px;
}
table.gridtable th {
	width: 400px;
	padding: 8px;
	background-color: #efefef;
}
table.gridtable td {
	width: 400px;
	padding: 8px;
	background-color: #ffffff;
}
</style>
</head>

<div>
<ul>
   	<table class='gridtable'>
   		<tr><th>Course</th>
   		<th>Score</th>
   		<th>学分</th></tr>
   		{%for line in stuview%}
   		<tr><td>{{line.cname}}</td>
   		<td>{{line.grade}}</td>
   		<td>{{line.chour}}</td></tr>
   		{%endfor%}
   		<tr><td></td></tr>
   		<tr><td>总成绩:{{student.grade}}</td>
   		<td float:left>总学分:{{tc}}</td>
   		</tr>
   	</table>
   	<br>
   	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
   	<form action='' method="POST"><input type="submit" name='submit' value="choose lesson"></input></form>
   	</p>
    </ul>
    </div>
{% endblock %} 